apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: world-data
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          imagePullPolicy: IfNotPresent
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - name: world
              mountPath: /data
          ports:
            - name: game-port
              containerPort: 25565
              hostPort: 25565
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: world-data
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
  - name: minecraft-port
    protocol: TCP
    port: 30001
    targetPort: game-port
    nodePort: 30001
